In [4]:
import pandas as pd
# fuzz is used to compare TWO strings
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
#import python-Levenshtein as lev

In [5]:
ct_final_data = "Resources/ct_final2.csv"
ct_final_df = pd.read_csv(ct_final_data)
ct_final_df.head(3)

,CTID,Title,Conditions,Study Type,Results First Posted,Company,Intervention
0,NCT02756624,"A Multi-Center, Vehicle-Controlled, Parallel-G...",Healthy Subjects,Interventional,26-Jul-17,"Nicox Ophthalmics, Inc.",Drug: AC-170 0.24%
1,NCT02756624,"A Multi-Center, Vehicle-Controlled, Parallel-G...",Healthy Subjects,Interventional,26-Jul-17,"Nicox Ophthalmics, Inc.",Drug: AC-170 Vehicle
2,NCT02756624,"A Multi-Center, Vehicle-Controlled, Parallel-G...",Healthy Subjects,Interventional,26-Jul-17,"ORA, Inc.",Drug: AC-170 0.24%

In [6]:
company_data = "Resources/Company_ID.csv"
company_df = pd.read_csv(company_data)
company_df.head(3)

,Symbol,Name,LastSale,MarketCap,ADR TSO,IPOyear,Sector,Industry,Summary Quote,Unnamed: 9
0,YI,"111, Inc.",3.7600,4.853105e+07,12907195.0,2018.0,Health Care,Medical/Nursing Services,https://www.nasdaq.com/symbol/yi,NaN
1,MMM,3M Company,173.9800,1.002867e+11,NaN,NaN,Health Care,Medical/Dental Instruments,https://www.nasdaq.com/symbol/mmm,NaN
2,AAC,"AAC Holdings, Inc.",0.9879,2.499575e+07,NaN,2014.0,Health Care,Medical Specialities,https://www.nasdaq.com/symbol/aac,NaN

In [15]:
ct_company = ct_final_df[['Company']]
print(ct_company.count())

ct_company.head(3)

Company    11468
dtype: int64

                   Company
0  Nicox Ophthalmics, Inc.
1  Nicox Ophthalmics, Inc.
2                ORA, Inc.

In [58]:
ct_output_co = ct_company.drop_duplicates()

count = ct_output_co.count()
print(count)
ct_output_co.head()

Company    866
dtype: int64

                                              Company
0                             Nicox Ophthalmics, Inc.
2                                           ORA, Inc.
4                                        Evolus, Inc.
6                                                 PPD
12  Otsuka Pharmaceutical Development & Commercial...

In [53]:
#ct_output_co_index = ct_output_co.set_index('Company')
#ct_output_co_index.head(3)

In [59]:
company_id = company_df[['Symbol', 'Name']]
count2 = company_id.count()
print(count2)
company_id.head(3)

Symbol    908
Name      908
dtype: int64

  Symbol                Name
0     YI           111, Inc.
1    MMM          3M Company
2    AAC  AAC Holdings, Inc.

In [52]:
#company_id_index = company_id.set_index('Name')
#ompany_id_index.head(3)

In [60]:
company_id2 = company_id.rename(columns={"Name":"Company"})
company_join = ct_output_co.join(company_id2, on='Company')
#count3 = company_combi.count()
#print(count3)
company_join.head(3)

ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat

In [50]:
#new_co_combi = company_combi.rename(columns={"Name":"stock_co", "Company":"ct_co"})
#new_co_combi.head(3)

In [37]:
matched_companies = []

for row in ct_output_co.index:
    company_name = ct_output_co.get_value(row,"Company")
    for columns in company_id.index:
        company_id_name=company_id.get_value(columns,"Name")
        matched_token=fuzz.partial_ratio(company_name,company_id_name)
        if matched_token >99:
            matched_companies.append([company_name,company_id_name,matched_token])

C:\Users\Dinesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  after removing the cwd from sys.path.
C:\Users\Dinesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

In [44]:
lists = matched_companies
lists

[['Evolus, Inc.', 'Evolus, Inc.', 100],
 ['Pfizer', 'Pfizer, Inc.', 100],
 ['Allergan', 'Allergan plc.', 100],
 ['Novartis', 'Novartis AG', 100],
 ['Eli Lilly and Company', 'Eli Lilly and Company', 100],
 ['VIVUS, Inc.', 'VIVUS, Inc.', 100],
 ['Johnson & Johnson Consumer Inc. (J&JCI)', 'Johnson & Johnson', 100],
 ['Johnson & Johnson Consumer and Personal Products Worldwide',
  'Johnson & Johnson',
  100],
 ['Theravance Biopharma', 'Theravance Biopharma, Inc.', 100],
 ['Catalyst Pharmaceuticals, Inc.', 'Catalyst Pharmaceuticals, Inc.', 100],
 ['GlaxoSmithKline', 'GlaxoSmithKline PLC', 100],
 ['Syneos Health', 'Syneos Health, Inc.', 100],
 ['Aerie Pharmaceuticals', 'Aerie Pharmaceuticals, Inc.', 100],
 ['Aclaris Therapeutics, Inc.', 'Aclaris Therapeutics, Inc.', 100],
 ['Portola Pharmaceuticals', 'Portola Pharmaceuticals, Inc.', 100],
 ['Ocular Therapeutix, Inc.', 'Ocular Therapeutix, Inc.', 100],
 ['Otonomy, Inc.', 'Otonomy, Inc.', 100],
 ['United Therapeutics', 'United Therapeutics Corporation', 100],
 ['AcelRx Pharmaceuticals, Inc.', 'AcelRx Pharmaceuticals, Inc.', 100],
 ['Boston Scientific Corporation', 'Boston Scientific Corporation', 100],
 ['Novo Nordisk A/S', 'Novo Nordisk A/S', 100],
 ['Biogen', 'Biogen Inc.', 100],
 ['Biogen', 'Vascular Biogenics Ltd.', 100],
 ['PLx Pharma', 'PLx Pharma Inc.', 100],
 ['Alimera Sciences', 'Alimera Sciences, Inc.', 100],
 ['The Medicines Company', 'The Medicines Company', 100],
 ['Retrophin, Inc.', 'Retrophin, Inc.', 100],
 ['Mallinckrodt', 'Mallinckrodt plc', 100],
 ['Arena Pharmaceuticals', 'Arena Pharmaceuticals, Inc.', 100],
 ['Abbott', 'Abbott Laboratories', 100],
 ['BioDelivery Sciences International',
  'BioDelivery Sciences International, Inc.',
  100],
 ['Cumberland Pharmaceuticals', 'Cumberland Pharmaceuticals Inc.', 100],
 ['BioMarin Pharmaceutical', 'BioMarin Pharmaceutical Inc.', 100],
 ['Gilead Sciences', 'Gilead Sciences, Inc.', 100],
 ['Teva Pharmaceutical Industries',
  'Teva Pharmaceutical Industries Limited',
  100],
 ['Bristol-Myers Squibb', 'Bristol-Myers Squibb Company', 100],
 ['Genzyme, a Sanofi Company', 'Sanofi', 100],
 ['Genzyme, a Sanofi Company', 'Sanofi', 100],
 ['Takeda', 'Takeda Pharmaceutical Company Limited', 100],
 ['Sanofi', 'Sanofi', 100],
 ['Sanofi', 'Sanofi', 100],
 ['Medtronic', 'Medtronic plc', 100],
 ['Celgene Corporation', 'Celgene Corporation', 100],
 ['Celgene Corporation', 'Celgene Corporation', 100],
 ['Aevi Genomic Medicine', 'Aevi Genomic Medicine, Inc.', 100],
 ['RTI Surgical', 'RTI Surgical Holdings, Inc.', 100],
 ['Recro Pharma, Inc.', 'Recro Pharma, Inc.', 100],
 ['Ultragenyx Pharmaceutical Inc', 'Ultragenyx Pharmaceutical Inc.', 100],
 ['Neos Therapeutics, Inc', 'Neos Therapeutics, Inc.', 100],
 ['Organogenesis', 'Organogenesis Holdings Inc. ', 100],
 ['Amgen', 'Amgen Inc.', 100],
 ['ResMed', 'ResMed Inc.', 100],
 ['Corcept Therapeutics', 'Corcept Therapeutics Incorporated', 100],
 ['Johnson & Johnson Pharmaceutical Research & Development, L.L.C.',
  'Johnson & Johnson',
  100],
 ['Xeris Pharmaceuticals', 'Xeris Pharmaceuticals, Inc.', 100],
 ['Johnson & Johnson Vision Care, Inc.', 'Johnson & Johnson', 100],
 ['Regeneron Pharmaceuticals', 'Regeneron Pharmaceuticals, Inc.', 100],
 ['Amicus Therapeutics', 'Amicus Therapeutics, Inc.', 100],
 ['Ironwood Pharmaceuticals, Inc.', 'Ironwood Pharmaceuticals, Inc.', 100],
 ['Nektar Therapeutics', 'Nektar Therapeutics', 100],
 ['Vertex Pharmaceuticals Incorporated',
  'Vertex Pharmaceuticals Incorporated',
  100],
 ['Instituto Grifols, S.A.', 'Grifols, S.A.', 100],
 ['Seattle Genetics, Inc.', 'Seattle Genetics, Inc.', 100],
 ['Incyte Corporation', 'Incyte Corporation', 100],
 ['Johnson & Johnson Healthcare Products Division of McNEIL-PPC, Inc.',
  'Johnson & Johnson',
  100],
 ['AbbVie', 'AbbVie Inc.', 100],
 ['Ionis Pharmaceuticals, Inc.', 'Ionis Pharmaceuticals, Inc.', 100],
 ['Supernus Pharmaceuticals, Inc.', 'Supernus Pharmaceuticals, Inc.', 100],
 ['Sanofi Pasteur, a Sanofi Company', 'Sanofi', 100],
 ['Sanofi Pasteur, a Sanofi Company', 'Sanofi', 100],
 ['Celgene', 'Celgene Corporation', 100],
 ['Celgene', 'Celgene Corporation', 100],
 ['Ligand Pharmaceuticals', 'Ligand Pharmaceuticals Incorporated', 100],
 ['Quest Diagnostics', 'Quest Diagnostics Incorporated', 100],
 ['Medigus Ltd', 'Medigus Ltd.', 100],
 ['Medigus Ltd', 'Medigus Ltd.', 100],
 ['Dermira, Inc.', 'Dermira, Inc.', 100],
 ['Sage Therapeutics', 'Sage Therapeutics, Inc.', 100],
 ['Kala Pharmaceuticals, Inc.', 'Kala Pharmaceuticals, Inc.', 100],
 ['Therapeutics, Inc.', 'Aclaris Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Acorda Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Aeglea BioTherapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'AgeX Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Agile Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Aileron Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Aimmune Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Akcea Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Akebia Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Akero Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Aldeyra Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Allogene Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Amicus Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Applied Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Aquestive Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Assertio Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Audentes Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Avenue Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Axsome Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Bellerophon Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'BioXcel Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Capricor Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Cara Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Celldex Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Checkpoint Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Cidara Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Cyclerion Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'CytomX Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Eidos Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Esperion Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Fate Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Five Prime Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Flexion Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Fulcrum Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'G1 Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Global Blood Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Halozyme Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Harpoon Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Heron Therapeutics, Inc.  ', 100],
 ['Therapeutics, Inc.', 'Hoth Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Intellia Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Jounce Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Karuna Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'LogicBio Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Magenta Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Marker Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Melinta Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Mersana Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Millendo Therapeutics, Inc. ', 100],
 ['Therapeutics, Inc.', 'Miragen Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Mirati Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Neon Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Neos Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'NeuBase Therapeutics, Inc. ', 100],
 ['Therapeutics, Inc.', 'Novus Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Obalon Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Odonate Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Onconova Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Onconova Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Oncternal Therapeutics, Inc. ', 100],
 ['Therapeutics, Inc.', 'Outlook Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Outlook Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Pluristem Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Protagonist Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Protalix BioTherapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Proteon Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Proteostasis Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'PTC Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Revance Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Rubius Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Sage Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Sangamo Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Sarepta Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Seelos Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Seres Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Soleno Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Soleno Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Sorrento Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Spark Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Spero Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Stemline Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Stoke Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Tenax Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'TG Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Trevi Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Turning Point Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Viking Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Viking Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'VistaGen Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Voyager Therapeutics, Inc.', 100],
 ['Therapeutics, Inc.', 'Y-mAbs Therapeutics, Inc.', 100],
 ['Neurocrine Biosciences', 'Neurocrine Biosciences, Inc.', 100],
 ['AMAG Pharmaceuticals, Inc.', 'AMAG Pharmaceuticals, Inc.', 100],
 ['Motif Bio', 'Motif Bio plc', 100],
 ['Motif Bio', 'Motif Bio plc', 100],
 ['Momenta Pharmaceuticals, Inc.', 'Momenta Pharmaceuticals, Inc.', 100],
 ['SIGA Technologies', 'SIGA Technologies Inc.', 100],
 ['Tetraphase Pharmaceuticals, Inc.', 'Tetraphase Pharmaceuticals, Inc.', 100],
 ['Flexion Therapeutics, Inc.', 'Flexion Therapeutics, Inc.', 100],
 ['Acorda Therapeutics', 'Acorda Therapeutics, Inc.', 100],
 ['Jazz Pharmaceuticals', 'Jazz Pharmaceuticals plc', 100],
 ['La Jolla Pharmaceutical Company', 'La Jolla Pharmaceutical Company', 100],
 ['Alnylam Pharmaceuticals', 'Alnylam Pharmaceuticals, Inc.', 100],
 ['Intersect ENT', 'Intersect ENT, Inc.', 100],
 ['Adamas Pharmaceuticals, Inc.', 'Adamas Pharmaceuticals, Inc.', 100],
 ['TherapeuticsMD', 'TherapeuticsMD, Inc.', 100],
 ['Rempex (a wholly owned subsidiary of Melinta Therapeutics, Inc.)',
  'Melinta Therapeutics, Inc.',
  100],
 ['Melinta Therapeutics, Inc.', 'Melinta Therapeutics, Inc.', 100],
 ['Dynavax Technologies Corporation', 'Dynavax Technologies Corporation', 100],
 ['Proteon Therapeutics', 'Proteon Therapeutics, Inc.', 100],
 ['Rigel Pharmaceuticals', 'Rigel Pharmaceuticals, Inc.', 100],
 ['Tenax Therapeutics, Inc.', 'Tenax Therapeutics, Inc.', 100],
 ['Lexicon Pharmaceuticals', 'Lexicon Pharmaceuticals, Inc.', 100],
 ['Alexion Pharmaceuticals', 'Alexion Pharmaceuticals, Inc.', 100],
 ['Heron Therapeutics', 'Heron Therapeutics, Inc.  ', 100],
 ['AEterna Zentaris', 'AEterna Zentaris Inc.', 100],
 ['Collegium Pharmaceutical, Inc.', 'Collegium Pharmaceutical, Inc.', 100],
 ['Silk Road Medical', 'Silk Road Medical, Inc.', 100],
 ['Exelixis', 'Exelixis, Inc.', 100],
 ['Omeros Corporation', 'Omeros Corporation', 100],
 ['Caladrius Biosciences, Inc.', 'Caladrius Biosciences, Inc.', 100],
 ['Merrimack Pharmaceuticals', 'Merrimack Pharmaceuticals, Inc.', 100],
 ['Intercept Pharmaceuticals', 'Intercept Pharmaceuticals, Inc.', 100],
 ['Perrigo Company', 'Perrigo Company', 100],
 ['Vanda Pharmaceuticals', 'Vanda Pharmaceuticals Inc.', 100],
 ['GTx', 'MeiraGTx Holdings plc', 100],
 ['Agile Therapeutics', 'Agile Therapeutics, Inc.', 100],
 ['Sunesis Pharmaceuticals', 'Sunesis Pharmaceuticals, Inc.', 100],
 ['ACADIA Pharmaceuticals Inc.', 'ACADIA Pharmaceuticals Inc.', 100],
 ['Inspire Medical Systems, Inc.', 'Inspire Medical Systems, Inc.', 100],
 ['Zogenix, Inc.', 'Zogenix, Inc.', 100],
 ['Navidea Biopharmaceuticals', 'Navidea Biopharmaceuticals, Inc.', 100],
 ['BioCryst Pharmaceuticals', 'BioCryst Pharmaceuticals, Inc.', 100],
 ['Zimmer Biomet', 'Zimmer Biomet Holdings, Inc.', 100],
 ['Avedro, Inc.', 'Avedro, Inc', 100],
 ['Radius Health, Inc.', 'Radius Health, Inc.', 100],
 ['Spectrum Pharmaceuticals, Inc', 'Spectrum Pharmaceuticals, Inc.', 100],
 ['Celsion', 'Celsion Corporation', 100],
 ['NuVasive', 'NuVasive, Inc.', 100],
 ['AtriCure, Inc.', 'AtriCure, Inc.', 100],
 ['Glaukos Corporation', 'Glaukos Corporation', 100],
 ['CTI BioPharma', 'CTI BioPharma Corp.', 100],
 ['Zosano Pharma Corporation', 'Zosano Pharma Corporation', 100],
 ['Aptevo Therapeutics', 'Aptevo Therapeutics Inc.', 100],
 ['CHF Solutions', 'CHF Solutions, Inc.', 100],
 ['Chiasma, Inc.', 'Chiasma, Inc.', 100]]

In [43]:
len(lists)

225

In [49]:
lists_df = pd.DataFrame(lists)
#lists_df = lists_df.transpose()
lists_df2 = lists_df.rename(columns={0:"ct_co_name", 1:"id_co_name", 2:"score"})
lists_df2.head()

              ct_co_name             id_co_name  score
0           Evolus, Inc.           Evolus, Inc.    100
1                 Pfizer           Pfizer, Inc.    100
2               Allergan          Allergan plc.    100
3               Novartis            Novartis AG    100
4  Eli Lilly and Company  Eli Lilly and Company    100

In [ ]:
ct_output_co